[2025-04-06T23:10:04.505+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:04.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:10:04.518+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:10:04.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:05.220+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:10:05.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:10:05.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:05.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.772 seconds
[2025-04-06T23:10:35.873+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:35.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:10:35.941+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:10:35.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:38.818+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:10:38.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:10:38.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:10:38.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 3.092 seconds
[2025-04-06T23:11:09.109+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:09.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:11:09.150+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:11:09.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:11.059+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:11:11.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:11:11.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:11.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 2.012 seconds
[2025-04-06T23:11:41.470+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:41.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:11:41.474+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:11:41.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:41.760+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:11:41.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:11:41.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:11:41.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.315 seconds
[2025-04-06T23:12:12.006+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:12.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:12:12.009+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:12:12.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:12.239+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:12:12.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:12:12.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:12.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.259 seconds
[2025-04-06T23:12:42.499+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:42.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:12:42.501+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:12:42.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:42.759+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:12:42.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:12:42.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:12:42.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.286 seconds
[2025-04-06T23:13:13.045+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:13.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:13:13.049+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:13:13.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:13.267+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:13:13.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:13:13.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:13.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.254 seconds
[2025-04-06T23:13:43.512+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:43.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:13:43.516+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:13:43.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:43.749+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:13:43.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:13:43.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:13:43.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.260 seconds
[2025-04-06T23:14:14.013+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:14.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:14:14.190+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:14:14.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:14.306+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:14:14.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:14:14.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:14.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.322 seconds
[2025-04-06T23:14:44.726+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:44.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:14:44.730+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:14:44.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:44.840+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:14:44.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:14:44.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:14:44.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.148 seconds
[2025-04-06T23:15:15.104+0000] {processor.py:186} INFO - Started process (PID=161) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:15.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:15:15.107+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:15:15.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:15.214+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:15:15.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:15:15.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:15.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.138 seconds
[2025-04-06T23:15:45.331+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:45.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:15:45.335+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:15:45.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:45.445+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:15:45.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:15:45.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:15:45.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.140 seconds
[2025-04-06T23:16:15.699+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:15.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:16:15.703+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:16:15.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:15.825+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:16:15.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:16:15.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:15.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.150 seconds
[2025-04-06T23:16:45.944+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:45.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:16:45.947+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:16:45.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:46.067+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:16:46.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:16:46.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:16:46.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.148 seconds
[2025-04-06T23:17:16.342+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:16.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:17:16.345+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:17:16.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:16.453+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:17:16.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:17:16.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:16.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.134 seconds
[2025-04-06T23:17:46.591+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:46.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:17:46.595+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:17:46.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:46.710+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:17:46.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:17:46.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:17:46.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.171 seconds
[2025-04-06T23:18:16.962+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:16.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:18:16.966+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:18:16.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:17.073+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:18:17.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:18:17.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:17.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.142 seconds
[2025-04-06T23:18:47.272+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:47.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:18:47.276+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:18:47.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:47.386+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:18:47.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:18:47.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:18:47.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.139 seconds
[2025-04-06T23:19:17.589+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:17.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:19:17.593+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:19:17.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:17.699+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:19:17.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:19:17.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:17.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.135 seconds
[2025-04-06T23:19:47.877+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:47.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:19:47.880+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:19:47.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:47.993+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:19:47.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:19:47.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:19:48.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.140 seconds
[2025-04-06T23:20:18.242+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:18.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:20:18.246+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:20:18.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:18.366+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:20:18.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:20:18.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:18.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.155 seconds
[2025-04-06T23:20:48.468+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:48.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:20:48.472+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:20:48.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:48.605+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:20:48.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:20:48.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:20:48.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.164 seconds
[2025-04-06T23:21:18.889+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:18.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:21:18.892+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:21:18.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:19.003+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:21:18.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:21:19.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:19.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.136 seconds
[2025-04-06T23:21:49.143+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:49.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:21:49.146+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:21:49.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:49.251+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:21:49.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:21:49.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:21:49.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.135 seconds
[2025-04-06T23:22:19.447+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:19.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:22:19.451+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:22:19.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:19.573+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:22:19.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:22:19.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:19.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.153 seconds
[2025-04-06T23:22:49.831+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:49.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:22:49.840+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:22:49.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:50.127+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:22:50.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:22:50.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:22:50.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.347 seconds
[2025-04-06T23:23:20.536+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:20.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:23:20.539+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:23:20.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:20.653+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:23:20.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:23:20.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:20.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.144 seconds
[2025-04-06T23:23:50.885+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:50.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:23:50.888+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:23:50.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:50.999+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:23:50.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:23:51.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:23:51.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.141 seconds
[2025-04-06T23:24:21.513+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:21.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:24:21.517+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:24:21.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:21.705+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:24:21.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:24:21.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:21.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.234 seconds
[2025-04-06T23:24:52.030+0000] {processor.py:186} INFO - Started process (PID=297) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:52.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:24:52.034+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:24:52.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:52.155+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:24:52.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:24:52.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:24:52.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.154 seconds
[2025-04-06T23:25:22.602+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:22.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:25:22.606+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:25:22.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:22.719+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:25:22.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:25:22.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:22.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.172 seconds
[2025-04-06T23:25:52.977+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:52.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:25:52.985+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:25:52.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:53.247+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:25:53.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:25:53.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:25:53.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.313 seconds
[2025-04-06T23:26:23.638+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:23.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:26:23.642+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:26:23.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:23.759+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:26:23.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:26:23.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:23.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.153 seconds
[2025-04-06T23:26:54.155+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:54.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:26:54.190+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:26:54.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:55.403+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:26:55.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:26:55.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:26:55.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.497 seconds
[2025-04-06T23:27:25.710+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:25.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:27:25.714+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:27:25.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:25.843+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:27:25.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:27:25.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:25.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.162 seconds
[2025-04-06T23:27:56.819+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:56.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:27:56.880+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:27:56.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:59.019+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:27:58.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:27:59.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:27:59.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 2.717 seconds
[2025-04-06T23:28:29.882+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:28:29.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:28:29.886+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:28:29.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:28:30.016+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:28:30.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:28:30.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:28:30.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.162 seconds
[2025-04-06T23:29:00.201+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:00.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:29:00.214+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:29:00.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:00.534+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:29:00.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:29:00.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:00.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.387 seconds
[2025-04-06T23:29:30.717+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:30.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:29:30.733+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:29:30.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:30.891+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:29:30.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:29:30.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:29:30.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.211 seconds
[2025-04-06T23:30:01.147+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:01.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:30:01.152+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:30:01.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:01.317+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:30:01.309+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:30:01.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:01.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.230 seconds
[2025-04-06T23:30:31.701+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:31.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:30:31.706+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:30:31.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:31.843+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:30:31.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:30:31.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:30:31.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.178 seconds
[2025-04-06T23:31:02.088+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:02.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:31:02.091+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:31:02.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:02.205+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:31:02.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:31:02.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:02.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.148 seconds
[2025-04-06T23:31:32.467+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:32.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:31:32.471+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:31:32.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:32.599+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:31:32.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:31:32.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:31:32.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.176 seconds
[2025-04-06T23:32:02.861+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:02.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:32:02.864+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:32:02.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:02.984+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:32:02.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:32:02.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:03.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.157 seconds
[2025-04-06T23:32:33.090+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:33.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:32:33.094+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:32:33.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:33.218+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:32:33.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:32:33.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:32:33.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.158 seconds
[2025-04-06T23:33:03.550+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:03.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:33:03.554+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:33:03.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:03.678+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:33:03.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:33:03.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:03.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.167 seconds
[2025-04-06T23:33:33.797+0000] {processor.py:186} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:33.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:33:33.802+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:33:33.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:33.969+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:33:33.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:33:33.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:33:34.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.210 seconds
[2025-04-06T23:34:04.130+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:04.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:34:04.135+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:34:04.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:04.298+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:34:04.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:34:04.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:04.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.201 seconds
[2025-04-06T23:34:34.403+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:34.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:34:34.407+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:34:34.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:34.542+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:34:34.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:34:34.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:34:34.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.170 seconds
[2025-04-06T23:35:04.875+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:04.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:35:04.878+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:35:04.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:04.985+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:35:04.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:35:04.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:05.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.153 seconds
[2025-04-06T23:35:35.328+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:35.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:35:35.331+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:35:35.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:35.442+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:35:35.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:35:35.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:35:35.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.139 seconds
[2025-04-06T23:36:05.626+0000] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:05.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:36:05.631+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:36:05.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:05.783+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:36:05.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:36:05.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:05.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.190 seconds
[2025-04-06T23:36:36.047+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:36.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:36:36.051+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:36:36.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:36.158+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:36:36.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:36:36.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:36:36.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.137 seconds
[2025-04-06T23:44:37.116+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:44:37.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:44:37.150+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:44:37.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:44:38.002+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:44:37.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:44:38.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:44:38.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.170 seconds
[2025-04-06T23:45:08.538+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:08.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:45:08.575+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:45:08.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:08.995+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:45:08.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:45:09.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:09.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.592 seconds
[2025-04-06T23:45:39.341+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:39.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:45:39.347+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:45:39.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:39.488+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:45:39.481+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:45:39.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:45:39.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.178 seconds
[2025-04-06T23:46:09.611+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:09.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:46:09.616+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:46:09.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:09.728+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:46:09.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:46:09.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:09.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.146 seconds
[2025-04-06T23:46:40.024+0000] {processor.py:186} INFO - Started process (PID=504) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:40.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:46:40.032+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:46:40.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:40.233+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:46:40.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:46:40.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:46:40.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.255 seconds
[2025-04-06T23:47:11.070+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:11.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:47:11.143+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:47:11.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:11.626+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:47:11.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:47:11.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:11.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.714 seconds
[2025-04-06T23:47:42.362+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:42.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:47:42.384+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:47:42.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:42.759+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:47:42.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:47:42.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:47:42.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.497 seconds
[2025-04-06T23:48:13.085+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:13.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:48:13.103+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:48:13.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:13.306+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:48:13.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:48:13.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:13.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.295 seconds
[2025-04-06T23:48:43.671+0000] {processor.py:186} INFO - Started process (PID=534) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:43.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:48:43.675+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:48:43.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:43.804+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:48:43.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:48:43.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:48:43.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.166 seconds
[2025-04-06T23:49:14.010+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:14.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:49:14.017+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:49:14.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:14.164+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:49:14.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:49:14.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:14.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.189 seconds
[2025-04-06T23:49:44.516+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:44.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:49:44.528+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:49:44.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:44.801+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:49:44.785+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:49:44.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:49:44.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.367 seconds
[2025-04-06T23:50:15.175+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:15.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:50:15.181+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:50:15.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:15.303+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:50:15.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:50:15.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:15.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.161 seconds
[2025-04-06T23:50:45.413+0000] {processor.py:186} INFO - Started process (PID=562) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:45.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:50:45.417+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:50:45.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:45.576+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:50:45.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:50:45.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:50:45.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.196 seconds
[2025-04-06T23:51:15.832+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:15.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:51:15.836+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:51:15.835+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:15.973+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:51:15.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:51:15.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:15.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.171 seconds
[2025-04-06T23:51:46.098+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:46.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:51:46.102+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:51:46.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:46.226+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:51:46.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:51:46.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:51:46.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.162 seconds
[2025-04-06T23:52:16.476+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:16.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:52:16.480+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:52:16.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:16.617+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:52:16.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:52:16.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:16.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.167 seconds
[2025-04-06T23:52:46.760+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:46.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:52:46.794+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:52:46.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:46.931+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:52:46.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:52:46.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:52:46.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.200 seconds
[2025-04-06T23:53:17.137+0000] {processor.py:186} INFO - Started process (PID=600) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:17.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:53:17.142+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:53:17.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:17.259+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:53:17.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:53:17.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:17.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.148 seconds
[2025-04-06T23:53:47.502+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:47.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:53:47.507+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:53:47.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:47.634+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:53:47.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:53:47.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:53:47.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.162 seconds
[2025-04-06T23:54:17.757+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:17.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:54:17.762+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:54:17.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:17.965+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:54:17.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:54:17.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:17.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.242 seconds
[2025-04-06T23:54:48.623+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:48.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:54:48.641+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:54:48.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:49.173+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:54:49.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:54:49.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:54:49.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.670 seconds
[2025-04-06T23:55:19.897+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:19.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:55:19.905+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:55:19.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:20.192+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:55:20.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:55:20.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:20.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.336 seconds
[2025-04-06T23:55:50.534+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:50.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:55:50.541+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:55:50.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:50.679+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:55:50.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:55:50.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:55:50.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.188 seconds
[2025-04-06T23:56:20.771+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:20.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:56:20.776+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:56:20.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:20.907+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:56:20.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:56:20.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:20.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.165 seconds
[2025-04-06T23:56:50.974+0000] {processor.py:186} INFO - Started process (PID=649) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:50.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:56:50.978+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:56:50.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:51.101+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:56:51.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:56:51.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:56:51.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.159 seconds
[2025-04-06T23:57:21.330+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:21.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:57:21.343+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:57:21.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:21.579+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:57:21.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:57:21.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:21.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.315 seconds
[2025-04-06T23:57:51.895+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:51.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:57:51.899+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:57:51.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:52.030+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:57:52.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:57:52.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:57:52.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.164 seconds
[2025-04-06T23:58:22.166+0000] {processor.py:186} INFO - Started process (PID=670) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:22.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:58:22.170+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:58:22.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:22.282+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:58:22.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:58:22.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:22.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.144 seconds
[2025-04-06T23:58:52.590+0000] {processor.py:186} INFO - Started process (PID=677) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:52.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:58:52.594+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:58:52.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:52.707+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:58:52.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:58:52.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:58:52.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.143 seconds
[2025-04-06T23:59:22.832+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:22.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:59:22.836+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:59:22.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:22.986+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:59:22.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:59:22.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:23.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.182 seconds
[2025-04-06T23:59:53.330+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:53.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-06T23:59:53.337+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:59:53.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:53.455+0000] {logging_mixin.py:190} INFO - [2025-04-06T23:59:53.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-06T23:59:53.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-06T23:59:53.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.155 seconds
