[2025-04-07T00:00:23.575+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:23.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:00:23.579+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:00:23.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:23.695+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:00:23.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:00:23.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:23.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.153 seconds
[2025-04-07T00:00:53.868+0000] {processor.py:186} INFO - Started process (PID=706) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:53.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:00:53.872+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:00:53.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:53.983+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:00:53.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:00:53.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:00:54.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.145 seconds
[2025-04-07T00:01:24.233+0000] {processor.py:186} INFO - Started process (PID=713) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:24.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:01:24.238+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:01:24.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:24.356+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:01:24.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:01:24.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:24.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.154 seconds
[2025-04-07T00:01:54.536+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:54.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:01:54.540+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:01:54.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:54.653+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:01:54.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:01:54.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:01:54.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.150 seconds
[2025-04-07T00:02:24.898+0000] {processor.py:186} INFO - Started process (PID=727) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:24.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:02:24.903+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:02:24.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:25.025+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:02:25.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:02:25.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:25.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.159 seconds
[2025-04-07T00:02:55.173+0000] {processor.py:186} INFO - Started process (PID=734) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:55.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:02:55.176+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:02:55.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:55.318+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:02:55.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:02:55.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:02:55.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.180 seconds
[2025-04-07T00:03:25.589+0000] {processor.py:186} INFO - Started process (PID=742) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:25.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:03:25.592+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:03:25.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:25.710+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:03:25.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:03:25.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:25.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.150 seconds
[2025-04-07T00:03:55.892+0000] {processor.py:186} INFO - Started process (PID=749) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:55.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:03:55.897+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:03:55.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:56.023+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:03:56.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:03:56.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:03:56.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.164 seconds
[2025-04-07T00:04:26.248+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:26.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:04:26.253+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:04:26.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:26.383+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:04:26.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:04:26.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:26.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.162 seconds
[2025-04-07T00:04:56.695+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:56.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:04:56.699+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:04:56.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:56.814+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:04:56.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:04:56.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:04:56.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.149 seconds
[2025-04-07T00:05:26.979+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:26.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:05:26.982+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:05:26.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:27.103+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:05:27.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:05:27.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:27.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.154 seconds
[2025-04-07T00:05:57.414+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:57.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:05:57.418+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:05:57.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:57.536+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:05:57.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:05:57.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:05:57.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.150 seconds
[2025-04-07T00:06:27.706+0000] {processor.py:186} INFO - Started process (PID=785) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:27.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:06:27.714+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:06:27.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:27.869+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:06:27.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:06:27.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:27.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.207 seconds
[2025-04-07T00:06:58.201+0000] {processor.py:186} INFO - Started process (PID=793) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:58.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:06:58.208+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:06:58.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:58.433+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:06:58.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:06:58.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:06:58.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.269 seconds
[2025-04-07T00:07:28.846+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:28.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:07:28.854+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:07:28.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:29.115+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:07:29.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:07:29.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:29.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.306 seconds
[2025-04-07T00:07:59.498+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:59.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:07:59.504+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:07:59.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:59.699+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:07:59.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:07:59.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:07:59.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.258 seconds
[2025-04-07T00:08:29.800+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:08:29.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:08:29.805+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:08:29.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:08:29.963+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:08:29.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:08:29.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:08:29.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.193 seconds
[2025-04-07T00:09:00.172+0000] {processor.py:186} INFO - Started process (PID=822) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:00.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:09:00.178+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:09:00.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:00.370+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:09:00.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:09:00.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:00.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.256 seconds
[2025-04-07T00:09:30.665+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:30.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:09:30.672+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:09:30.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:30.887+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:09:30.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:09:30.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:09:30.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.263 seconds
[2025-04-07T00:10:01.302+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:01.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:10:01.367+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:10:01.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:01.649+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:10:01.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:10:01.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:01.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.412 seconds
[2025-04-07T00:10:32.060+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:32.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:10:32.064+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:10:32.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:32.304+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:10:32.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:10:32.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:10:32.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.279 seconds
[2025-04-07T00:11:02.684+0000] {processor.py:186} INFO - Started process (PID=851) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:02.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:11:02.691+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:11:02.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:02.904+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:11:02.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:11:02.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:02.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.264 seconds
[2025-04-07T00:11:33.011+0000] {processor.py:186} INFO - Started process (PID=858) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:33.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:11:33.017+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:11:33.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:33.189+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:11:33.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:11:33.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:11:33.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.225 seconds
[2025-04-07T00:12:03.873+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:03.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:12:03.891+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:12:03.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:04.431+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:12:04.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:12:04.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:04.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.680 seconds
[2025-04-07T00:12:35.129+0000] {processor.py:186} INFO - Started process (PID=873) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:35.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:12:35.179+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:12:35.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:35.932+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:12:35.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:12:35.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:12:36.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.095 seconds
[2025-04-07T00:13:06.417+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:06.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:13:06.464+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:13:06.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:06.663+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:13:06.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:13:06.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:06.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.311 seconds
[2025-04-07T00:13:36.837+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:36.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:13:36.844+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:13:36.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:37.039+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:13:37.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:13:37.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:13:37.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.235 seconds
[2025-04-07T00:14:07.372+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:07.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:14:07.390+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:14:07.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:07.684+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:14:07.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:14:07.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:07.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.362 seconds
[2025-04-07T00:14:38.318+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:38.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:14:38.352+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:14:38.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:38.866+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:14:38.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:14:38.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:14:38.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.659 seconds
[2025-04-07T00:15:09.065+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:09.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:15:09.072+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:15:09.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:09.353+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:15:09.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:15:09.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:09.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.330 seconds
[2025-04-07T00:15:39.648+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:39.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:15:39.656+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:15:39.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:39.859+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:15:39.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:15:39.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:15:39.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.259 seconds
[2025-04-07T00:16:10.126+0000] {processor.py:186} INFO - Started process (PID=923) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:10.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:16:10.132+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:16:10.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:10.342+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:16:10.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:16:10.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:10.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.251 seconds
[2025-04-07T00:16:40.573+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:40.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:16:40.579+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:16:40.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:40.786+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:16:40.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:16:40.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:16:40.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.248 seconds
[2025-04-07T00:17:11.050+0000] {processor.py:186} INFO - Started process (PID=937) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:11.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:17:11.055+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:17:11.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:11.259+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:17:11.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:17:11.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:11.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.250 seconds
[2025-04-07T00:17:41.466+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:41.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:17:41.473+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:17:41.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:41.790+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:17:41.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:17:41.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:17:41.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.376 seconds
[2025-04-07T00:18:11.976+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:11.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:18:11.993+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:18:11.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:12.278+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:18:12.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:18:12.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:12.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.341 seconds
[2025-04-07T00:18:42.588+0000] {processor.py:186} INFO - Started process (PID=958) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:42.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:18:42.594+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:18:42.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:42.796+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:18:42.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:18:42.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:18:42.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.248 seconds
[2025-04-07T00:19:13.046+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:13.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:19:13.055+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:19:13.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:13.267+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:19:13.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:19:13.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:13.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.256 seconds
[2025-04-07T00:19:43.730+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:43.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:19:43.736+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:19:43.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:43.952+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:19:43.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:19:43.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:19:43.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.257 seconds
[2025-04-07T00:20:14.152+0000] {processor.py:186} INFO - Started process (PID=984) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:14.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:20:14.161+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:20:14.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:14.397+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:20:14.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:20:14.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:14.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.281 seconds
[2025-04-07T00:20:44.745+0000] {processor.py:186} INFO - Started process (PID=991) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:44.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:20:44.752+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:20:44.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:44.974+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:20:44.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:20:44.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:20:45.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.272 seconds
[2025-04-07T00:21:15.206+0000] {processor.py:186} INFO - Started process (PID=999) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:15.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:21:15.255+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:21:15.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:15.568+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:21:15.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:21:15.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:15.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.480 seconds
[2025-04-07T00:21:45.722+0000] {processor.py:186} INFO - Started process (PID=1007) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:45.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:21:45.728+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:21:45.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:45.986+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:21:45.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:21:45.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:21:46.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.314 seconds
[2025-04-07T00:22:16.293+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:16.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:22:16.300+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:22:16.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:16.484+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:22:16.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:22:16.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:16.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.231 seconds
[2025-04-07T00:22:46.732+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:46.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:22:46.740+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:22:46.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:47.057+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:22:47.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:22:47.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:22:47.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.373 seconds
[2025-04-07T00:23:17.203+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:17.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:23:17.209+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:23:17.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:17.457+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:23:17.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:23:17.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:17.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.295 seconds
[2025-04-07T00:23:47.748+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:47.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:23:47.756+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:23:47.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:47.960+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:23:47.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:23:47.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:23:47.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.251 seconds
[2025-04-07T00:24:18.192+0000] {processor.py:186} INFO - Started process (PID=1042) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:18.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:24:18.201+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:24:18.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:18.487+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:24:18.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:24:18.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:18.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.353 seconds
[2025-04-07T00:24:48.945+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:48.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:24:48.952+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:24:48.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:49.178+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:24:49.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:24:49.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:24:49.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.282 seconds
[2025-04-07T00:25:19.615+0000] {processor.py:186} INFO - Started process (PID=1057) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:19.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:25:19.619+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:25:19.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:19.799+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:25:19.788+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:25:19.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:19.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.225 seconds
[2025-04-07T00:25:49.937+0000] {processor.py:186} INFO - Started process (PID=1064) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:49.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:25:49.944+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:25:49.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:50.155+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:25:50.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:25:50.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:25:50.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.324 seconds
[2025-04-07T00:26:20.803+0000] {processor.py:186} INFO - Started process (PID=1071) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:20.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:26:20.854+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:26:20.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:21.413+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:26:21.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:26:21.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:21.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.791 seconds
[2025-04-07T00:26:51.921+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:51.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:26:51.936+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:26:51.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:52.152+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:26:52.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:26:52.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:26:52.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.335 seconds
[2025-04-07T00:27:22.487+0000] {processor.py:186} INFO - Started process (PID=1084) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:22.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:27:22.504+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:27:22.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:22.877+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:27:22.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:27:22.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:22.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.527 seconds
[2025-04-07T00:27:53.036+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:53.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:27:53.043+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:27:53.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:53.281+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:27:53.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:27:53.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:27:53.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.294 seconds
[2025-04-07T00:28:23.556+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:23.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:28:23.563+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:28:23.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:23.813+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:28:23.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:28:23.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:23.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.296 seconds
[2025-04-07T00:28:54.054+0000] {processor.py:186} INFO - Started process (PID=1105) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:54.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:28:54.060+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:28:54.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:54.284+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:28:54.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:28:54.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:28:54.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.266 seconds
[2025-04-07T00:29:24.518+0000] {processor.py:186} INFO - Started process (PID=1112) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:24.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:29:24.526+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:29:24.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:24.708+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:29:24.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:29:24.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:24.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.234 seconds
[2025-04-07T00:29:55.266+0000] {processor.py:186} INFO - Started process (PID=1119) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:55.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:29:55.270+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:29:55.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:55.487+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:29:55.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:29:55.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:29:55.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.254 seconds
[2025-04-07T00:30:25.626+0000] {processor.py:186} INFO - Started process (PID=1126) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:25.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:30:25.633+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:30:25.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:25.899+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:30:25.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:30:25.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:25.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.308 seconds
[2025-04-07T00:30:56.228+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:56.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:30:56.235+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:30:56.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:56.445+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:30:56.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:30:56.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:30:56.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.256 seconds
[2025-04-07T00:31:26.609+0000] {processor.py:186} INFO - Started process (PID=1140) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:26.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:31:26.617+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:31:26.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:26.849+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:31:26.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:31:26.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:26.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.282 seconds
[2025-04-07T00:31:57.400+0000] {processor.py:186} INFO - Started process (PID=1149) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:57.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:31:57.479+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:31:57.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:58.223+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:31:58.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:31:58.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:31:58.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.096 seconds
[2025-04-07T00:32:28.588+0000] {processor.py:186} INFO - Started process (PID=1155) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:28.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:32:28.606+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:32:28.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:28.829+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:32:28.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:32:28.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:28.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.296 seconds
[2025-04-07T00:32:59.158+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:59.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:32:59.164+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:32:59.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:59.384+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:32:59.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:32:59.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:32:59.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.267 seconds
[2025-04-07T00:33:29.563+0000] {processor.py:186} INFO - Started process (PID=1170) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:33:29.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:33:29.569+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:33:29.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:33:29.840+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:33:29.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:33:29.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:33:29.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.324 seconds
[2025-04-07T00:34:00.082+0000] {processor.py:186} INFO - Started process (PID=1177) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:00.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:34:00.091+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:34:00.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:00.317+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:34:00.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:34:00.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:00.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.278 seconds
[2025-04-07T00:34:30.592+0000] {processor.py:186} INFO - Started process (PID=1184) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:30.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:34:30.598+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:34:30.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:30.833+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:34:30.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:34:30.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:34:30.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.307 seconds
[2025-04-07T00:35:01.036+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:01.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:35:01.041+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:35:01.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:01.266+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:35:01.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:35:01.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:01.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.284 seconds
[2025-04-07T00:35:31.753+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:31.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:35:31.780+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:35:31.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:32.211+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:35:32.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:35:32.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:35:32.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.561 seconds
[2025-04-07T00:36:02.626+0000] {processor.py:186} INFO - Started process (PID=1205) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:02.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:36:02.633+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:36:02.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:02.863+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:36:02.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:36:02.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:02.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.292 seconds
[2025-04-07T00:36:33.451+0000] {processor.py:186} INFO - Started process (PID=1212) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:33.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:36:33.556+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:36:33.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:34.082+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:36:34.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:36:34.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:36:34.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.789 seconds
[2025-04-07T00:37:04.744+0000] {processor.py:186} INFO - Started process (PID=1219) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:04.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:37:04.826+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:37:04.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:05.383+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:37:05.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:37:05.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:05.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.837 seconds
[2025-04-07T00:37:35.895+0000] {processor.py:186} INFO - Started process (PID=1226) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:35.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:37:35.902+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:37:35.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:36.109+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:37:36.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:37:36.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:37:36.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.249 seconds
[2025-04-07T00:38:06.298+0000] {processor.py:186} INFO - Started process (PID=1233) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:06.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:38:06.303+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:38:06.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:06.505+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:38:06.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:38:06.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:06.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.240 seconds
[2025-04-07T00:38:36.874+0000] {processor.py:186} INFO - Started process (PID=1240) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:36.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:38:36.885+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:38:36.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:37.341+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:38:37.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:38:37.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:38:37.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.580 seconds
[2025-04-07T00:39:10.953+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:10.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:39:11.076+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:39:11.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:12.921+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:39:12.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:39:12.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:13.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 2.643 seconds
[2025-04-07T00:39:43.914+0000] {processor.py:186} INFO - Started process (PID=1254) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:43.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:39:43.962+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:39:43.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:44.530+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:39:44.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:39:44.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:39:44.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.761 seconds
[2025-04-07T00:40:15.060+0000] {processor.py:186} INFO - Started process (PID=1261) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:15.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:40:15.070+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:40:15.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:15.272+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:40:15.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:40:15.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:15.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.251 seconds
[2025-04-07T00:40:45.514+0000] {processor.py:186} INFO - Started process (PID=1268) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:45.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:40:45.521+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:40:45.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:45.745+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:40:45.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:40:45.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:40:45.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.271 seconds
[2025-04-07T00:41:15.961+0000] {processor.py:186} INFO - Started process (PID=1275) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:15.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:41:15.985+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:41:15.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:16.304+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:41:16.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:41:16.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:16.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.395 seconds
[2025-04-07T00:41:46.633+0000] {processor.py:186} INFO - Started process (PID=1282) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:46.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:41:46.658+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:41:46.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:47.016+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:41:47.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:41:47.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:41:47.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.480 seconds
[2025-04-07T00:42:18.261+0000] {processor.py:186} INFO - Started process (PID=1290) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:18.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:42:18.350+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:42:18.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:19.691+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:42:19.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:42:19.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:19.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.785 seconds
[2025-04-07T00:42:50.365+0000] {processor.py:186} INFO - Started process (PID=1305) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:50.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:42:50.384+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:42:50.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:50.692+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:42:50.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:42:50.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:42:50.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.381 seconds
[2025-04-07T00:43:21.211+0000] {processor.py:186} INFO - Started process (PID=1313) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:21.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:43:21.218+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:43:21.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:21.500+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:43:21.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:43:21.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:21.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.351 seconds
[2025-04-07T00:43:51.997+0000] {processor.py:186} INFO - Started process (PID=1320) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:52.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:43:52.011+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:43:52.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:52.247+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:43:52.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:43:52.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:43:52.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.297 seconds
[2025-04-07T00:44:22.686+0000] {processor.py:186} INFO - Started process (PID=1326) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:22.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:44:22.691+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:44:22.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:22.883+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:44:22.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:44:22.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:22.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.224 seconds
[2025-04-07T00:44:53.549+0000] {processor.py:186} INFO - Started process (PID=1333) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:53.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:44:53.687+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:44:53.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:54.593+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:44:54.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:44:54.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:44:54.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 1.157 seconds
[2025-04-07T00:45:24.717+0000] {processor.py:186} INFO - Started process (PID=1340) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:24.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:45:24.722+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:45:24.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:24.912+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:45:24.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:45:24.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:24.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.229 seconds
[2025-04-07T00:45:55.333+0000] {processor.py:186} INFO - Started process (PID=1348) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:55.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:45:55.341+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:45:55.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:55.576+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:45:55.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:45:55.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:45:55.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.310 seconds
[2025-04-07T00:46:26.049+0000] {processor.py:186} INFO - Started process (PID=1356) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:26.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:46:26.059+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:46:26.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:26.332+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:46:26.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:46:26.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:26.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.349 seconds
[2025-04-07T00:46:56.872+0000] {processor.py:186} INFO - Started process (PID=1363) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:56.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:46:56.877+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:46:56.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:57.114+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:46:57.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:46:57.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:46:57.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.291 seconds
[2025-04-07T00:47:27.567+0000] {processor.py:186} INFO - Started process (PID=1370) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:27.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:47:27.575+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:47:27.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:27.827+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:47:27.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:47:27.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:27.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.305 seconds
[2025-04-07T00:47:58.299+0000] {processor.py:186} INFO - Started process (PID=1377) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:58.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:47:58.306+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:47:58.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:58.545+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:47:58.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:47:58.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:47:58.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.303 seconds
[2025-04-07T00:48:29.012+0000] {processor.py:186} INFO - Started process (PID=1385) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:29.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:48:29.021+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:48:29.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:29.226+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:48:29.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:48:29.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:29.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.256 seconds
[2025-04-07T00:48:59.378+0000] {processor.py:186} INFO - Started process (PID=1392) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:59.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:48:59.385+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:48:59.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:59.587+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:48:59.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:48:59.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:48:59.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.252 seconds
[2025-04-07T00:49:29.913+0000] {processor.py:186} INFO - Started process (PID=1400) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:49:29.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:49:29.922+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:49:29.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:49:30.140+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:49:30.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:49:30.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:49:30.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.321 seconds
[2025-04-07T00:50:00.627+0000] {processor.py:186} INFO - Started process (PID=1407) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:00.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:50:00.652+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:50:00.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:01.013+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:50:00.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:50:01.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:01.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.500 seconds
[2025-04-07T00:50:31.486+0000] {processor.py:186} INFO - Started process (PID=1414) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:31.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:50:31.497+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:50:31.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:31.759+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:50:31.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:50:31.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:50:31.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.320 seconds
[2025-04-07T00:51:02.266+0000] {processor.py:186} INFO - Started process (PID=1421) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:02.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:51:02.285+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:51:02.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:02.626+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:51:02.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:51:02.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:02.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.482 seconds
[2025-04-07T00:51:33.097+0000] {processor.py:186} INFO - Started process (PID=1428) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:33.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:51:33.112+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:51:33.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:33.310+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:51:33.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:51:33.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:51:33.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.276 seconds
[2025-04-07T00:52:03.730+0000] {processor.py:186} INFO - Started process (PID=1435) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:03.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:52:03.743+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:52:03.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:03.949+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:52:03.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:52:03.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:03.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.279 seconds
[2025-04-07T00:52:34.384+0000] {processor.py:186} INFO - Started process (PID=1442) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:34.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:52:34.389+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:52:34.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:34.625+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:52:34.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:52:34.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:52:34.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.306 seconds
[2025-04-07T00:53:05.079+0000] {processor.py:186} INFO - Started process (PID=1448) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:05.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:53:05.085+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:53:05.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:05.306+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:53:05.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:53:05.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:05.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.269 seconds
[2025-04-07T00:53:35.680+0000] {processor.py:186} INFO - Started process (PID=1455) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:35.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:53:35.685+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:53:35.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:35.885+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:53:35.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:53:35.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:53:35.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.239 seconds
[2025-04-07T00:54:06.079+0000] {processor.py:186} INFO - Started process (PID=1462) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:06.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:54:06.088+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:54:06.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:06.326+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:54:06.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:54:06.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:06.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.302 seconds
[2025-04-07T00:54:36.586+0000] {processor.py:186} INFO - Started process (PID=1469) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:36.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:54:36.591+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:54:36.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:36.789+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:54:36.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:54:36.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:54:36.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.243 seconds
[2025-04-07T00:55:07.339+0000] {processor.py:186} INFO - Started process (PID=1476) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:07.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:55:07.346+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:55:07.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:07.547+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:55:07.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:55:07.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:07.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.247 seconds
[2025-04-07T00:55:37.674+0000] {processor.py:186} INFO - Started process (PID=1484) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:37.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:55:37.681+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:55:37.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:37.925+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:55:37.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:55:37.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:55:37.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.296 seconds
[2025-04-07T00:56:08.194+0000] {processor.py:186} INFO - Started process (PID=1491) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:08.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:56:08.198+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:56:08.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:08.334+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:56:08.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:56:08.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:08.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.173 seconds
[2025-04-07T00:56:38.484+0000] {processor.py:186} INFO - Started process (PID=1498) to work on /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:38.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_jobs_data_scrapper.py for tasks to queue
[2025-04-07T00:56:38.488+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:56:38.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:38.646+0000] {logging_mixin.py:190} INFO - [2025-04-07T00:56:38.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_jobs_data_scrapper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jobs_data_scrapper.py", line 7, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 617, in __init__
    if start_date and start_date.tzinfo:
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'tzinfo'
[2025-04-07T00:56:38.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jobs_data_scrapper.py
[2025-04-07T00:56:38.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_jobs_data_scrapper.py took 0.192 seconds
